FROM golang:1.24-alpine AS builder
WORKDIR /app

# Копируем файлы зависимостей и загружаем их
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код и собираем приложение
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o producer ./cmd/producer

FROM alpine:3.22
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/producer .
COPY --from=builder /app/model.json ./
CMD ["./producer"]